Created new imageType input for error images
blackbaud/skyux-errors pull request #6
Opened 2018-11-19 17:31 UTC by blackbaud-conorwright

Created new image type input
Moved image loading to the sky-error-image component

Resolves: blackbaud/skyux2#2034
Docs: blackbaud/skyux2#2179

2018-11-26 17:45 UTC, Blackbaud-SteveBrush requested changes
We'll need a visual test for the custom error type so that it's easy to test (manually), and to have a screenshot of its current state.

2018-11-27 15:27 UTC, Blackbaud-SteveBrush commented
We'll need a companion pull request into skyux2 to update the demo.

2018-11-27 19:04 UTC, blackbaud-conorwright commented
Added the visual testing and created an issue for making demo changes after this merges: blackbaud/skyux2#2190

2018-11-28 20:36 UTC, Blackbaud-SteveBrush reviewed
Just one comment.

2018-11-28 20:36 UTC, Blackbaud-SteveBrush commented on src/app/visual/error/error-visual.component.html
> +    </sky-error-description>
Let's throw the `<sky-error-action>` in here (like the other examples), just to be sure.

2018-11-29 15:07 UTC, Blackbaud-ToddRoberts commented
How does this interact with errorType? If you set errorType and imageType, which one wins?

2018-11-29 15:11 UTC, blackbaud-conorwright commented
@Blackbaud-ToddRoberts They aren't tied together and it will behave the same as it does right now when you provide a custom image and an errorType. It will show both images

2018-11-29 15:47 UTC, Blackbaud-ToddRoberts reviewed
Seems fine to me, I assume if no consumer has brought up the possibility of ending up with 2 images yet that it's not an issue.

2018-11-29 16:53 UTC, closed without merging

2018-11-29 19:46 UTC, blackbaud-conorwright commented
closed in favor of: https://github.com/blackbaud/skyux-errors/pull/7